# LU-decomposition primer

In [1]:
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library
import numpy as np # For random matrix generation

### Generate random matrix:

**Two ways** currently I am aware of:
* numpy.random.rand(m, n) - m x n matrix with random *real* elements
* numpy.random.randint(high, size=(m, n)) - m x n matrix of *integers* from half-interval [0, high)

#### Let's use second way for simplicity

In [2]:
# just for test
print(np.random.rand(3, 3)) # 3x3 is dimensions here random real matrix

[[0.20216218 0.04279659 0.03325659]
 [0.36824896 0.06626978 0.08890535]
 [0.59878259 0.35684501 0.62278456]]


In [3]:
A = np.random.randint(50, size=(3, 3)) # random 3x3 matrix of integers from range [0, 50)
print(A)

[[38 36  4]
 [47 44 44]
 [ 5 25 49]]


In [4]:
P, L, U = scipy.linalg.lu(A)

## Lower triangle matrix:

In [5]:
print (L)

[[1.         0.         0.        ]
 [0.10638298 1.         0.        ]
 [0.80851064 0.02094241 1.        ]]


## Upper triangle matrix:

In [6]:
print(U)

[[ 47.          44.          44.        ]
 [  0.          20.31914894  44.31914894]
 [  0.           0.         -32.5026178 ]]


## Permutation matrix:

In [7]:
print(P)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


## Check correctness

This formula must be correct:
$$A = P * L * U$$

In [14]:
print("Source matrix А")
print(A)

Source matrix А
[[38 36  4]
 [47 44 44]
 [ 5 25 49]]


In [13]:
LU = np.matmul(L, U)
print(LU)

[[47. 44. 44.]
 [ 5. 25. 49.]
 [38. 36.  4.]]


In [10]:
PLU = np.matmul(P, LU)
print(PLU)

[[38. 36.  4.]
 [47. 44. 44.]
 [ 5. 25. 49.]]


In [11]:
print(np.allclose(A, PLU))

True
